---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true

- name: Update all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

- name: Install required system packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"
  notify: Purge old packages
