services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/:/etc/ssl/certs
      - /var/log/nginx:/var/log/nginx
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
    networks:
{% for item in backend[inventory_hostname] %}
      {{ item.network }}:
{% endfor %}

networks:
{% for item in backend[inventory_hostname] %}
  {{ item.network }}:
    external: true
{% endfor %}