---
- name: Copy all certificates to /usr/local/share/ca-certificates/
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/share/ca-certificates/{{ item | basename }}"
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "files/*.crt"
  notify: Updating CA certificates
