services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus
{% if prometheus_external_networks is defined and prometheus_external_networks %}
{% for ext_net in prometheus_external_networks %}
      - {{ ext_net }}
{% endfor %}
{% endif %}

networks:
  prometheus:
    name: prometheus_default
{% if prometheus_external_networks is defined and prometheus_external_networks %}
{% for ext_net in prometheus_external_networks %}
  {{ ext_net }}:
    external: true
    name: {{ ext_net }}
{% endfor %}
{% endif %}

volumes:
  prometheus-data:
    name: prometheus-data
