---
- name: Install Docker
  ansible.builtin.apt:
    name: '{{ item.name }}'
    state: present
  with_items:
    - { name: docker }
    - { name: docker-compose }

- name: Add users to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Create the docker.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Configure the proxy
  ansible.builtin.template:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: '0644'
  notify:
    - Reload systemd docker
    - Restart docker service

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
