---
- name: Create a VM on Proxmox
  community.general.proxmox_kvm:
    api_host: "{{ proxmox.api_host }}"
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_pass }}"
    node: "{{ proxmox.node }}"
    name: "{{ item.name }}"
    vmid: "{{ item.vmid }}"
    memory: "{{ item.memory }}"
    cores: "{{ item.cores }}"
    sockets: "{{ item.sockets }}"
    description: "{{ item.description | default(omit) }}"
    tags: "{{ item.tags | default(omit) }}"
    scsi:
      scsi0: 'local-lvm:{{ item.disk_size }}'
    scsihw: "virtio-scsi-single"
    net:
      net0: "macaddr={{ item.mac_address }},virtio,bridge={{ item.bridge }},firewall=1"
    boot: "order=scsi0;ide2;net0"
    onboot: true
    ide:
      ide2: "{{ item.iso_path }},media=cdrom"
    ostype: "l26"
    agent: 1
    state: present
  loop: "{{ vm_list }}"
