---
- name: Create directories
  ansible.builtin.file:
    path: "{{ grafana_directory }}{{ item.name }}"
    state: directory
    mode: '0755'
  with_items:
    - { name: "/" }
    - { name: "/certs" }
    - { name: "/dashboards" }

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ grafana_directory }}/docker-compose.yml"
    mode: "0644"

- name: Copy grafana files
  ansible.builtin.copy:
    src: "files/"
    dest: "{{ grafana_directory }}"
    owner: "1000"
    group: "1000"
    mode: "755"
  notify: Restart grafana

- name: Start docker
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: "{{ grafana_directory }}"
  changed_when: false
