{
 "title": "Synology",
 "tags": [
  "synology",
  "Prometheus",
  "snmp_exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Server:", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(modelName, instance)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(modelName, job)" } },
   { "name": "interfacebits", "query": "8" },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ifName{job=~'$job',instance=~'$instance'},ifName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Summary - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modelName{job=~'$job',instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "serialNumber{job=~'$job',instance=~'$instance'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "upgradeAvailable{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "version{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpuFanStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "systemFanStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "systemStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "powerStatus{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "RAID Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "raidStatus{job=~'$job',instance=~'$instance', raidName=~\"Volume.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalSwap{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrSystemUptime{job=~'$job',instance=~'$instance'} / 100"
    }
   ]
  },
  {
   "title": "Hard Drives",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diskTemperature{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "diskType{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "diskStatus{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "diskModel{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "The percentage of CPU time spent processing user-level code, calculated over the last minute.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ssCpuIdle{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "System Temp",
   "type": "gauge",
   "description": "The temperature of Disk Station uses Celsius degree",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 / memTotalReal{job=~'$job',instance=~'$instance'}) * (memTotalReal{job=~'$job',instance=~'$instance'} - memAvailReal{job=~'$job',instance=~'$instance'} - memCached{job=~'$job',instance=~'$instance'} - memBuffer{job=~'$job',instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'}) / memTotalSwap{job=~'$job',instance=~'$instance'} * 100"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "ifPhysAddress{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "ifSpeed{job=~'$job',instance=~'$instance'}"
    },
    {
     "expr": "ifOperStatus{job=~'$job',instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Volume 1 Usage %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"})",
     "legendFormat": "Volume 1"
    }
   ]
  },
  {
   "title": "Volume 2 Usage %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"})",
     "legendFormat": "Volume 2"
    }
   ]
  },
  {
   "title": "Volume 3 Usage %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"})",
     "legendFormat": "Volume 2"
    }
   ]
  },
  {
   "title": "Current Connected Users / Service",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "serviceUsers{job=~'$job',instance=~'$instance'}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  { "title": "CPU / RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Utilisation - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ssCpuUser{job=~'$job',instance=~'$instance'}",
     "legendFormat": "User"
    },
    {
     "expr": "ssCpuSystem{job=~'$job',instance=~'$instance'}",
     "legendFormat": "System"
    },
    {
     "expr": "100 - ssCpuIdle{job=~'$job',instance=~'$instance'} - ssCpuUser{job=~'$job',instance=~'$instance'} - ssCpuSystem{job=~'$job',instance=~'$instance'}",
     "legendFormat": "I/O Wait"
    }
   ]
  },
  {
   "title": "System Load (minute ave.) - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "laLoadInt{job=~'$job',instance=~'$instance', laNames=\"Load-1\"} / 100",
     "legendFormat": "{{laNames}}"
    },
    {
     "expr": "laLoadInt{job=~'$job',instance=~'$instance', laNames=\"Load-5\"} / 100",
     "legendFormat": "{{laNames}}"
    },
    {
     "expr": "laLoadInt{job=~'$job',instance=~'$instance', laNames=\"Load-15\"} / 100",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "RAM Utilisation - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 / memTotalReal{job=~'$job',instance=~'$instance'}) * (memTotalReal{job=~'$job',instance=~'$instance'} - memAvailReal{job=~'$job',instance=~'$instance'} - memCached{job=~'$job',instance=~'$instance'} - memBuffer{job=~'$job',instance=~'$instance'})",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Physical Memory - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalReal{job=~'$job',instance=~'$instance'} ",
     "legendFormat": "Size"
    },
    {
     "expr": "memTotalReal{job=~'$job',instance=~'$instance'} - (memShared{job=~'$job',instance=~'$instance'} + memCached{job=~'$job',instance=~'$instance'} + memBuffer{job=~'$job',instance=~'$instance'} + memAvailReal{job=~'$job',instance=~'$instance'})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "memBuffer{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memCached{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memShared{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Shared"
    },
    {
     "expr": "memAvailReal{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "SWAP Utilisation % - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'}) / memTotalSwap{job=~'$job',instance=~'$instance'} * 100",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "SWAP Utilisation - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalSwap{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Size"
    },
    {
     "expr": "(memTotalSwap{job=~'$job',instance=~'$instance'} - memAvailSwap{job=~'$job',instance=~'$instance'})",
     "legendFormat": "Used"
    },
    {
     "expr": "memAvailSwap{job=~'$job',instance=~'$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "HDD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Storage Usage % - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"})",
     "legendFormat": "Volume 1"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"})",
     "legendFormat": "Volume 2"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"})",
     "legendFormat": "Volume 3"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"})",
     "legendFormat": "Volume 4"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"})",
     "legendFormat": "Volume 5"
    },
    {
     "expr": "100-(100/raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"}*raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"})",
     "legendFormat": "Volume 5"
    }
   ]
  },
  {
   "title": "Storage Usage - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 1\"}",
     "legendFormat": "Volume 1"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 2\"}",
     "legendFormat": "Volume 2"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 3\"}",
     "legendFormat": "Volume 3"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 4\"}",
     "legendFormat": "Volume 4"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 5\"}",
     "legendFormat": "Volume 5"
    },
    {
     "expr": "raidTotalSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"} - raidFreeSize{job=~'$job',instance=~'$instance',raidName=\"Volume 6\"}",
     "legendFormat": "Volume 5"
    }
   ]
  },
  {
   "title": "Disk read MB/s - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(diskIONReadX{job=~'$job',instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "{{diskI0Device}}"
    }
   ]
  },
  {
   "title": "Disk write MB/s - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(diskIONWrittenX{job=~'$job',instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "{{diskI0Device}}"
    }
   ]
  },
  {
   "title": "Disk read io/s - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(diskIOReads{job=~'$job',instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "{{diskI0Device}}"
    }
   ]
  },
  {
   "title": "Disk write io/s - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(diskIOWrites{job=~'$job',instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "{{diskI0Device}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Host - Received Network Traffic - $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=~'$job',instance=~'$instance'}[$__rate_interval])*$interfacebits",
     "legendFormat": "{{label_name}}{{ifName}}"
    }
   ]
  },
  {
   "title": "Host - Sent Network Traffic - $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{job=~'$job',instance=~'$instance'}[$__rate_interval])*$interfacebits  ",
     "legendFormat": "{{label_name}}{{ifName}}"
    }
   ]
  },
  {
   "title": "Users / Service - $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "serviceUsers{job=~'$job',instance=~'$instance'}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Errors - $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ifInDiscards{job=~'$job',instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "Discards In {{ifName}}"
    },
    {
     "expr": "rate(ifInErrors{job=~'$job',instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "Errors In {{ifName}}"
    },
    {
     "expr": "rate(ifOutDiscards{job=~'$job',instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "Discards Out {{ifName}}"
    },
    {
     "expr": "rate(ifOutErrors{job=~'$job',instance=~'$instance'}[$__rate_interval])",
     "legendFormat": "Errors Out {{ifName}}"
    }
   ]
  },
  { "title": "exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "SNMP Exporter - Scrape Time - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{job=~'$job',instance=~'$instance'}",
     "legendFormat": "{{label_name}}{{job}}"
    }
   ]
  }
 ]
}