---
- name: Create Semaphore base directory
  ansible.builtin.file:
    path: "{{ semaphore_directory }}{{ item.name }}"
    state: directory
    owner: "1001"
    group: "1001"
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Deploy docker-compose configuration
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ semaphore_directory }}/docker-compose.yml"

- name: Start semaphore
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: "{{ semaphore_directory }}"
  changed_when: false
