---
- name: Create Semaphore base directory
  file:
    path: "{{ semaphore_directory }}{{ item.name }}"
    state: directory
    owner: "1001"
    group: "1001"
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Deploy docker-compose configuration
  template:
    src: docker-compose.yml
    dest: "{{ semaphore_directory }}/docker-compose.yml"

- name: Start semaphore
  shell: docker-compose -f {{ semaphore_directory }}/docker-compose.yml up -d
