---
- name: Create Privatebin base directory
  ansible.builtin.file:
    path: "{{ privatebin_directory }}{{ item.name }}"
    state: directory
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Deploy docker-compose configuration
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ privatebin_directory }}/docker-compose.yml"
    mode: '0644'
  notify: Restart privatebin

- name: Deploy privatebin configuration
  ansible.builtin.template:
    src: conf.php
    dest: "{{ privatebin_directory }}/"
    mode: '0644'
  notify: Restart privatebin

- name: Start privatebin
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: "{{ privatebin_directory }}"
  changed_when: false
