---
- name: Create required directories
  file:
    path: "{{ cadvisor_directory }}{{ item.name }}"
    state: directory
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ cadvisor_directory }}/docker-compose.yml"
  notify: Restart cadvisor

- name: Start cadvisor containers
  command: docker-compose -f {{ cadvisor_directory }}/docker-compose.yml up -d