---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ cadvisor_directory }}{{ item.name }}"
    state: directory
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ cadvisor_directory }}/docker-compose.yml"
    mode: '0644'
  notify: Restart cadvisor

- name: Start cadvisor containers
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: "{{ cadvisor_directory }}"
  changed_when: false
