---
- name: Remove old proxy lines from bashrc
  lineinfile:
    path: /etc/bash.bashrc
    state: absent
    regexp: '^export (http_proxy|https_proxy|no_proxy)='

- name: Remove old proxy lines from /etc/environment
  lineinfile:
    path: /etc/environment
    state: absent
    regexp: '^(http_proxy|https_proxy|no_proxy)='

- name: Remove old APT proxy if it exists
  lineinfile:
    path: /etc/apt/apt.conf.d/01proxy
    state: absent
    regexp: '^Acquire::http::Proxy '

- name: Set APT proxy configuration
  lineinfile:
    path: /etc/apt/apt.conf.d/01proxy
    line: 'Acquire::http::Proxy "{{ proxy }}";'
    create: yes

- name: Set global environment proxy configuration
  lineinfile:
    path: /etc/environment
    line: '{{ item }}'
  loop:
    - 'http_proxy="{{ proxy }}"'
    - 'https_proxy="{{ proxy }}"'
    - 'no_proxy="{{ no_proxy }}"'

- name: Set user-specific proxy configuration (bashrc)
  lineinfile:
    path: /etc/bash.bashrc
    line: '{{ item }}'
  loop:
    - 'export http_proxy="{{ proxy }}"'
    - 'export https_proxy="{{ proxy }}"'
    - 'export no_proxy="{{ no_proxy }}"'
