---
- name: Remove old proxy lines from bashrc
  lineinfile:
    path: /etc/bash.bashrc
    state: absent
    regexp: '^export (http_proxy|https_proxy|no_proxy)='

- name: Remove old proxy lines from /etc/environment
  lineinfile:
    path: /etc/environment
    state: absent
    regexp: '^(http_proxy|https_proxy|no_proxy)='

- name: Remove old APT proxy if it exists
  lineinfile:
    path: /etc/apt/apt.conf.d/01proxy
    state: absent
    regexp: '^Acquire::http::Proxy '

- name: Set APT proxy configuration block
  blockinfile:
    path: /etc/apt/apt.conf.d/01proxy
    create: yes
    block: |
      Acquire::http::Proxy "{{ http_proxy }}";
      Acquire::https::Proxy "{{ https_proxy }}";

- name: Set global environment proxy configuration
  lineinfile:
    path: /etc/environment
    line: '{{ item }}'
  loop:
    - 'http_proxy="{{ http_proxy }}"'
    - 'https_proxy="{{ https_proxy }}"'
    - 'no_proxy="{{ no_proxy }}"'

- name: Set user-specific proxy configuration (bashrc)
  lineinfile:
    path: /etc/bash.bashrc
    line: '{{ item }}'
  loop:
    - 'export http_proxy="{{ http_proxy }}"'
    - 'export https_proxy="{{ https_proxy }}"'
    - 'export no_proxy="{{ no_proxy }}"'
