---
- name: Remove old proxy lines from bashrc
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    state: absent
    regexp: '^export (http_proxy|https_proxy|no_proxy)='

- name: Remove old proxy lines from /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    state: absent
    regexp: '^(http_proxy|https_proxy|no_proxy)='

- name: Remove old APT proxy if it exists
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/01proxy
    state: absent
    regexp: '^Acquire::http::Proxy '

- name: Set APT proxy configuration block
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/01proxy
    create: true
    mode: '0644'
    block: |
      Acquire::http::Proxy "{{ http_proxy }}";
      Acquire::https::Proxy "{{ https_proxy }}";

- name: Set global environment proxy configuration
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: '{{ item }}'
  loop:
    - 'http_proxy="{{ http_proxy }}"'
    - 'https_proxy="{{ https_proxy }}"'
    - 'no_proxy="{{ no_proxy }}"'

- name: Set user-specific proxy configuration (bashrc)
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    line: '{{ item }}'
  loop:
    - 'export http_proxy="{{ http_proxy }}"'
    - 'export https_proxy="{{ https_proxy }}"'
    - 'export no_proxy="{{ no_proxy }}"'
