---
- name: Create Vaultwarden base directory
  file:
    path: "{{ vaultwarden_directory }}{{ item.name }}"
    state: directory
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Deploy docker-compose configuration
  template:
    src: docker-compose.yml
    dest: "{{ vaultwarden_directory }}/docker-compose.yml"

- name: Create log directory for Vaultwarden
  file:
    path: "{{ vaultwarden_log_file | dirname }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'
  notify: Restart vaultwarden

- name: Create Vaultwarden log file
  file:
    path: "{{ vaultwarden_log_file }}"
    state: touch
    owner: "1000"
    group: "1000"
    mode: '0644'
  notify: Restart vaultwarden

- name: Start Vaultwarden using Docker Compose
  shell: docker-compose -f {{ vaultwarden_directory }}/docker-compose.yml up -d
