---
- name: Create Vaultwarden base directory
  ansible.builtin.file:
    path: "{{ vaultwarden_directory }}{{ item.name }}"
    state: directory
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Deploy docker-compose configuration
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ vaultwarden_directory }}/docker-compose.yml"
    mode: '0644'

- name: Create log directory for Vaultwarden
  ansible.builtin.file:
    path: "{{ vaultwarden_log_file | dirname }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'
  notify: Restart vaultwarden

- name: Create Vaultwarden log file
  ansible.builtin.file:
    path: "{{ vaultwarden_log_file }}"
    state: touch
    owner: "1000"
    group: "1000"
    mode: '0644'
  notify: Restart vaultwarden

- name: Start Vaultwarden using Docker Compose
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: "{{ vaultwarden_directory }}"
  changed_when: false
