---
- name: Create directories
  ansible.builtin.file:
    path: "{{ snmpexporter_directory }}{{ item.name }}"
    state: directory
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ snmpexporter_directory }}/docker-compose.yml"
    mode: "0644"

- name: Start docker
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: "{{ snmpexporter_directory }}"
  changed_when: false
