services:
  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
