---
- name: Reload systemd docker
  ansible.builtin.systemd:
    name: docker
    daemon_reload: true

- name: Restart docker service
  ansible.builtin.service:
    name: docker
    state: restarted
