services:
  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    restart: unless-stopped
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
{% if blackbox_bind_ip is defined %}
    ports:
      - "{{ blackbox_bind_ip }}:9115:9115"
{% endif %}
    command:
      - '--config.file=/config/blackbox.yml'
