---
- name: Create Squid base directory
  ansible.builtin.file:
    path: "{{ squid_directory }}{{ item.name }}"
    state: directory
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Create log directory for Squid
  ansible.builtin.file:
    path: "{{ squid.log_file_volume.split(':')[0] | dirname }}"
    state: directory
    mode: '0755'
  when: squid.log_file_volume is defined

- name: Create Squid access log file
  ansible.builtin.file:
    path: "{{ squid.log_file_volume.split(':')[0] }}"
    state: touch
    mode: '0777'
  when: squid.log_file_volume is defined

- name: Deploy docker-compose configuration
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ squid_directory }}/docker-compose.yml"
    mode: '0644'

- name: Deploy squid configuration
  ansible.builtin.copy:
    src: "{{ (squid_conf_source_override | default(role_path ~ '/files')) ~ '/' }}"
    dest: "{{ squid_directory }}/squid"
    mode: '0644'
  notify: Reload squid configuration

- name: Start service
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: "{{ squid_directory }}"
  changed_when: false
