---
- name: Create directories
  ansible.builtin.file:
    path: "{{ prometheus_directory }}{{ item.name }}"
    state: directory
    mode: '0755'
  with_items:
    - { name: "/" }

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ prometheus_directory }}/docker-compose.yml"
    mode: "0644"

- name: Template prometheus config
  ansible.builtin.template:
    src: "prometheus.yml"
    dest: "{{ prometheus_directory }}/prometheus.yml"
    owner: "1000"
    group: "1000"
    mode: "744"
  notify: Restart prometheus

- name: Start docker
  ansible.builtin.command: docker-compose up -d
  args:
    chdir: "{{ prometheus_directory }}"
  changed_when: false
