grafana_directory: /opt/grafana
# grafana_provisioning_source_override: /opt/grafana/files

grafana_external_networks:
  - loki_default
  - prometheus_default

grafana_global:
  root_url: https://grafana.company.com
  auth_anonymous_enabled: true
  timezone: America/New York
  week_start: Monday
  analytics: false
  analytics_reporting: false
  analytics_check_updates: false
  analytics_check_plugin_updates: false
  analytics_feedback_links: false
  feature_toogles: alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode

grafana_security:
  admin_user: admin
  admin_email: admin@company.com
  admin_password: changeme

grafana_users:
  allow_sign_up: false
  verify_email: true
  default_language: en-US
  default_org_name: Company
  default_org_role: Viewer

grafana_smtp:
  enabled: true
  host: smtp.company.com:465
  user: grafana@company.com
  pass: changeme
  from_addr: grafana@company.com
  from_name: grafana@company.com
